import numpy                    as np 
import pandas                   as pd
import pylab                    as pl
import matplotlib.pyplot        as plt
import sklearn.metrics          as met
import sklearn.datasets         as dt
import sklearn.linear_model     as li
import sklearn.model_selection  as ms
import scipy                    as linalg
